---
# tasks file for sbt

- name: Include OS Specific Vars
  include_vars: "{{item}}"
  with_first_found:
    - "vars-{{ansible_distribution}}-sbt.yml"
    - "default.yml"

- name: Include OS Specific
  include: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-sbt.yml"
    - "default.yml"
