--- 
- name: install key (apt)
  become: yes
  apt_key:
    keyserver: 'hkp://keyserver.ubuntu.com:80' 
    id: '2EE0EA64E40A89B84B2DF73499E82A75642AC823'

- name: install SBT repo (apt)
  become: yes
  apt_repository:
    repo: deb {{sbt_repo}} /
    filename: sbt
    state: present

- name: Install SBT
  become: yes
  apt: 
    pkg: sbt 
    update_cache: yes
    state: latest
  notify: check_sbt_version