---
# tasks file for intellij

- name: ensure download location exists
  file: 
    path: "{{intellij_download_location}}" 
    state: directory

- name: download tar file
  get_url: 
    url: "{{intellij_download_url}}"
    dest: "{{intellij_download_location}}/ideaIC-no-jdk.tar.gz"

- name: ensure install location exists
  file: 
    path: "{{intellij_install_location}}/{{user}}" 
    state: directory

- name: Extract intellij Tar
  unarchive: 
    src: "{{intellij_download_location}}/ideaIC-no-jdk.tar.gz"
    dest: "{{intellij_install_location}}/{{user}}"
    remote_src: yes

- name: change owner
  shell: chown -R {{user}}:{{user}} "{{intellij_install_location}}/{{user}}"

- name: Create Desktop Shortcut
  template:
    src: intellij.desktop
    dest: /home/{{user}}/Desktop/intellij.desktop
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0744