---
# tasks file for vs-code

- name: Include OS Specific Vars
  include_vars: "{{item}}"
  with_first_found:
    - "vars-{{ansible_distribution}}-vs-code.yml"
    - "default.yml"

- name: Include OS Specific
  include: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-vs-code.yml"
    - "default.yml"

